version: '3.7'

services:
  projectx-build:
    image: projectx-build
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - projectx 
      
  projectx-postgres:
    image: postgres:12.4
    container_name: projectx-postgres
    restart: unless-stopped
    networks:
      - projectx 
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  projectx-rabbitmq:
    image: rabbitmq:3-management
    container_name: projectx-rabbitmq
    restart: unless-stopped
    networks:
      - projectx 
    ports:
      - 15673:15672
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
      
  projectx-realtime:
    image: projectx-realtime
    build:
      context: .
      dockerfile: src/Services/ProjectX.Realtime/ProjectX.Realtime.API/Dockerfile
    restart: on-failure
    networks:
      - projectx 
    ports:
      - 5003:80
    depends_on:
      - projectx-build
      - projectx-rabbitmq
    environment:
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Connection__HostName=projectx-rabbitmq
      - IdentityUrl=http://localhost:5000

  projectx-identity:
    image: projectx-identity
    build:
      context: .
      dockerfile: src/Services/ProjectX.Identity/ProjectX.Identity.API/Dockerfile
    restart: on-failure
    depends_on:
      - projectx-build
      - projectx-rabbitmq
      - projectx-postgres
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - RabbitMq__Connection__HostName=projectx-rabbitmq
      - IdentityUrl=http://127.0.0.1:5000
      - ConnectionStrings__DbConnection=Host=projectx-postgres;Database=ProjectX.Identity;Username=postgres;Password=root
    networks:
      - projectx
    ports:
      - "5000:5000"

  projectx-blog:
    image: projectx-blog
    build:
      context: .
      dockerfile: src/Services/ProjectX.Blog/ProjectX.Blog.API/Dockerfile
    restart: on-failure
    networks:
      - projectx 
    ports:
      - 5001:80
    depends_on:
      - projectx-build
      - projectx-rabbitmq
      - projectx-postgres
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RabbitMq__Connection__HostName=projectx-rabbitmq
      - IdentityUrl=http://projectx-identity:5000
      - ConnectionStrings__DbConnection=Host=projectx-postgres;Database=ProjectX.Blog;Username=postgres;Password=root

networks:
  projectx:
    name: projectx-network