version: '3.7'

services:
  projectx-build:
    image: projectx-build
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - projectx 

  projectx-identity:
    image: projectx-identity
    build:
      context: .
      dockerfile: src/Services/ProjectX.Identity/ProjectX.Identity.API/Dockerfile
    restart: on-failure
    depends_on:
      - projectx-build
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - RabbitMq__Connection__HostName=projectx-rabbitmq
      - RedisOptions__Server__Hosts__0__Host=projectx-redis
      - RedisOptions__Server__Password=RedisPassword
      - IdentityUrl=http://projectx-identity:5000 # for jwt validation
      - ExternalIdentityUrl=http://127.0.0.1:5000 # for swagger
      - ConnectionStrings__DbConnection=Host=projectx-postgres;Database=ProjectX.Identity;Username=postgres;Password=root
    networks:
      - projectx
    ports:
      - "5000:5000"

  projectx-blog:
    image: projectx-blog
    build:
      context: .
      dockerfile: src/Services/ProjectX.Blog/ProjectX.Blog.API/Dockerfile
    restart: on-failure
    networks:
      - projectx 
    ports:
      - 5001:5001 # This is for debugging, we can reach our services through NGINX
    depends_on:
      - projectx-build
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5001
      - RabbitMq__Connection__HostName=projectx-rabbitmq
      - IdentityUrl=http://projectx-identity:5000 # for jwt validation
      - ExternalIdentityUrl=http://127.0.0.1:5000 # for swagger
      - ConnectionStrings__DbConnection=Host=projectx-postgres;Database=ProjectX.Blog;Username=postgres;Password=root
  
  projectx-messenger:
    image: projectx-messenger
    build:
      context: .
      dockerfile: src/Services/ProjectX.Messenger/ProjectX.Messenger.API/Dockerfile
    restart: on-failure
    networks:
      - projectx 
    ports:
      # Map several ports to test scaling and nginx load balancer
      # Use docker-compose up --scale projectx-messenger=2 -d
      - 5002-5003:5002 
    depends_on:
      - projectx-build
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5002
      - RabbitMq__Connection__HostName=projectx-rabbitmq
      - IdentityUrl=http://projectx-identity:5000 # for jwt validation
      - ExternalIdentityUrl=http://127.0.0.1:5000 # for swagger
      - ConnectionStrings__DbConnection=Host=projectx-postgres;Database=ProjectX.Messenger;Username=postgres;Password=root

  projectx-realtime:
    image: projectx-realtime
    build:
      context: .
      dockerfile: src/Services/ProjectX.Realtime/ProjectX.Realtime.API/Dockerfile
    restart: on-failure
    networks:
      - projectx 
    ports:
      - 5004:5004
    depends_on:
      - projectx-build
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5004
      - RabbitMq__Connection__HostName=projectx-rabbitmq
      - IdentityUrl=http://projectx-identity:5000 # for jwt validation
      - ExternalIdentityUrl=http://127.0.0.1:5000 # for swagger

networks:
  projectx:
    name: projectx-network
    external: true